/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basdatgui;

import AllClass.Pelajar;
import AllClass.PelajarDAO;
import util.DatabaseConnection;

/**
 *
 * @author Regina Anky Chandra
 */
public class BiodataFrame extends javax.swing.JFrame {

    /**
     * Creates new form BerandaFrame
     */
    public BiodataFrame() {
        initComponents();
        Pelajar p = Pelajar.getCurrentPelajar();
        if (p != null) {
            tampilkanDataPelajar(p);
        }
    }
    private void tampilkanDataPelajar(Pelajar p) {
            txtNama.setText(p.getNama());
            txtID.setText(p.getIdPelajar());
            txtTanggalLahir.setText(p.getTanggalLahir());
            txtAlamat.setText(p.getAlamat());
            txtEmail.setText(p.getEmail());
            txtNomorHp.setText(p.getNomorHp());
            txtJenisKelamin.setText(p.getJenisKelamin());
            txtAsalSekolah.setText(p.getAsalSekolah());
            txtAngkatan.setText(p.getAngkatan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        btnBeranda = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnBiodata = new javax.swing.JButton();
        labelJudulContent = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelTanggalLahir = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelNoHp = new javax.swing.JLabel();
        labelJenisKelamin = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtTanggalLahir = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNomorHp = new javax.swing.JTextField();
        txtJenisKelamin = new javax.swing.JTextField();
        labelJenisKelamin1 = new javax.swing.JLabel();
        txtAsalSekolah = new javax.swing.JTextField();
        labelJenisKelamin2 = new javax.swing.JLabel();
        txtAngkatan = new javax.swing.JTextField();
        SimpanBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        panelMain.setMinimumSize(new java.awt.Dimension(800, 600));
        panelMain.setPreferredSize(new java.awt.Dimension(1200, 800));

        panelHeader.setBackground(new java.awt.Color(255, 204, 204));

        labelJudul.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelJudul.setText("Intel Bimbingan Belajar");

        btnBeranda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBeranda.setText("BERANDA");
        btnBeranda.setBorderPainted(false);
        btnBeranda.setContentAreaFilled(false);
        btnBeranda.setFocusPainted(false);
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        btnJadwal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnJadwal.setText("JADWAL");
        btnJadwal.setBorderPainted(false);
        btnJadwal.setContentAreaFilled(false);
        btnJadwal.setFocusPainted(false);
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });

        btnPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPembayaran.setText("PEMBAYARAN");
        btnPembayaran.setBorderPainted(false);
        btnPembayaran.setContentAreaFilled(false);
        btnPembayaran.setFocusPainted(false);
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnBiodata.setBorderPainted(false);
        btnBiodata.setContentAreaFilled(false);
        btnBiodata.setFocusPainted(false);
        btnBiodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiodataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 540, Short.MAX_VALUE)
                .addComponent(btnBeranda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPembayaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBiodata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBiodata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBeranda)
                        .addComponent(btnJadwal)
                        .addComponent(btnPembayaran)))
                .addGap(25, 25, 25))
        );

        panelMain.add(panelHeader);

        labelJudulContent.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelJudulContent.setText("Biodata Pelajar");
        panelMain.add(labelJudulContent);

        labelNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNama.setText("Nama: ");
        panelMain.add(labelNama);

        labelID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelID.setText("ID: ");
        panelMain.add(labelID);

        labelTanggalLahir.setText("Tanggal Lahir: ");
        panelMain.add(labelTanggalLahir);

        labelAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAlamat.setText("Alamat: ");
        panelMain.add(labelAlamat);

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setText("Email: ");
        panelMain.add(labelEmail);

        labelNoHp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNoHp.setText("Nomor HP: ");
        panelMain.add(labelNoHp);

        labelJenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelJenisKelamin.setText("Jenis Kelamin: ");
        panelMain.add(labelJenisKelamin);

        txtNama.setEditable(false);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        panelMain.add(txtNama);

        txtID.setEditable(false);
        panelMain.add(txtID);

        txtTanggalLahir.setEditable(false);
        panelMain.add(txtTanggalLahir);

        txtAlamat.setEditable(false);
        panelMain.add(txtAlamat);

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        panelMain.add(txtEmail);

        txtNomorHp.setEditable(false);
        panelMain.add(txtNomorHp);

        txtJenisKelamin.setEditable(false);
        panelMain.add(txtJenisKelamin);

        labelJenisKelamin1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelJenisKelamin1.setText("Asal Sekolah: ");
        panelMain.add(labelJenisKelamin1);

        txtAsalSekolah.setEditable(false);
        panelMain.add(txtAsalSekolah);

        labelJenisKelamin2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelJenisKelamin2.setText("Angkatan: ");
        panelMain.add(labelJenisKelamin2);

        txtAngkatan.setEditable(false);
        panelMain.add(txtAngkatan);

        SimpanBtn.setText("Simpan");
        panelMain.add(SimpanBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBiodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiodataActionPerformed
        BiodataFrame biodata = new BiodataFrame ();
        biodata.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBiodataActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
//        PembayaranFrame pembayaran = new PembayaranFrame();
//        pembayaran.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
//        JadwalFrame jadwal = new JadwalFrame();
//        jadwal.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed
        BerandaFrame beranda = new BerandaFrame();
        beranda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBerandaActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed
    
//    private void tampilkanDataPelajar(String idPelajar) {
//        try (Connection conn = DatabaseConnection.getConnection()) {
//            String sql = "SELECT * FROM pelajar WHERE id_pelajar = ?";
//            PreparedStatement stmt = conn.prepareStatement(sql);
//            stmt.setString(1, idPelajar);
//            ResultSet rs = stmt.executeQuery();
//
//            if (rs.next()) {
//                txtNama.setText(rs.getString("nama"));
//                txtTanggalLahir.setText(rs.getString("tanggal_lahir"));
//                txtAlamat.setText(rs.getString("alamat"));
//                txtEmail.setText(rs.getString("email"));
//                txtNomorHP.setText(rs.getString("nomor_hp"));
//                txtJenisKelamin.setText(rs.getString("jenis_kelamin"));
//                txtAsalSekolah.setText(rs.getString("asal_Sekolah"));
//                txtAngkatan.setText(rs.getString("angkatan"));
//            } else {
//                JOptionPane.showMessageDialog(this, "Data tidak ditemukan.");
//            }
//
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Gagal memuat data.");
//        }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SimpanBtn;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnBiodata;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelJenisKelamin;
    private javax.swing.JLabel labelJenisKelamin1;
    private javax.swing.JLabel labelJenisKelamin2;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJudulContent;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNoHp;
    private javax.swing.JLabel labelTanggalLahir;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtAngkatan;
    private javax.swing.JTextField txtAsalSekolah;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJenisKelamin;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomorHp;
    private javax.swing.JTextField txtTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
